In [2]:
import gzip
import pandas as pd
import requests
from io import BytesIO

def load_data_from_github(url):
    response = requests.get(url)
    compressed_file = BytesIO(response.content)
    with gzip.open(compressed_file, 'rt') as file:
        data = pd.read_csv(file, sep='\t', header=None)
    return data

url = 'https://raw.githubusercontent.com/laiguokun/multivariate-time-series-data/master/electricity/electricity.txt.gz'
data = load_data_from_github(url)

In [3]:
data.head(15)

0
0   14.000000,69.000000,234.000000,415.000000,215....
1   18.000000,92.000000,312.000000,556.000000,292....
2   21.000000,96.000000,312.000000,560.000000,272....
3   20.000000,92.000000,312.000000,443.000000,213....
4   22.000000,91.000000,312.000000,346.000000,190....
5   20.000000,92.000000,187.000000,340.000000,178....
6   20.000000,91.000000,138.000000,376.000000,199....
7   20.000000,92.000000,8.000000,361.000000,187.00...
8   13.000000,91.000000,7.000000,259.000000,144.00...
9   11.000000,96.000000,8.000000,402.000000,172.00...
10  64.000000,113.000000,13.000000,446.000000,191....
11  53.000000,142.000000,11.000000,551.000000,200....
12  26.000000,158.000000,11.000000,532.000000,236....
13  10.000000,147.000000,13.000000,364.000000,187....
14  28.000000,122.000000,17.000000,294.000000,197....

In [4]:
test1=data

In [5]:
test1.head(10)

0
0  14.000000,69.000000,234.000000,415.000000,215....
1  18.000000,92.000000,312.000000,556.000000,292....
2  21.000000,96.000000,312.000000,560.000000,272....
3  20.000000,92.000000,312.000000,443.000000,213....
4  22.000000,91.000000,312.000000,346.000000,190....
5  20.000000,92.000000,187.000000,340.000000,178....
6  20.000000,91.000000,138.000000,376.000000,199....
7  20.000000,92.000000,8.000000,361.000000,187.00...
8  13.000000,91.000000,7.000000,259.000000,144.00...
9  11.000000,96.000000,8.000000,402.000000,172.00...

In [6]:
print(test1.head())
print(test1.shape)
print(test1.dtypes)

                                                   0
0  14.000000,69.000000,234.000000,415.000000,215....
1  18.000000,92.000000,312.000000,556.000000,292....
2  21.000000,96.000000,312.000000,560.000000,272....
3  20.000000,92.000000,312.000000,443.000000,213....
4  22.000000,91.000000,312.000000,346.000000,190....
(26304, 1)
0    object
dtype: object


In [41]:
import pandas as pd

# Set display options
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.width', None)        # Adjust display width to show all columns
pd.set_option('display.max_colwidth', None) # Display full content of each cell

# Display the first few rows of the dataset
print(test1.head())


    0     1      2      3      4       5     6       7      8      9      10   \
0  14.0  69.0  234.0  415.0  215.0  1056.0  29.0   840.0  226.0  265.0  179.0   
1  18.0  92.0  312.0  556.0  292.0  1363.0  29.0  1102.0  271.0  340.0  235.0   
2  21.0  96.0  312.0  560.0  272.0  1240.0  29.0  1025.0  270.0  300.0  221.0   
3  20.0  92.0  312.0  443.0  213.0   845.0  24.0   833.0  179.0  211.0  170.0   
4  22.0  91.0  312.0  346.0  190.0   647.0  16.0   733.0  186.0  179.0  142.0   

     11     12     13     14      15    16     17     18     19    20   \
0  148.0  112.0  171.0  229.0  1001.0  49.0  162.0  594.0   88.0  34.0   
1  192.0  143.0  213.0  301.0  1223.0  64.0  216.0  758.0  126.0  39.0   
2  171.0  132.0  185.0  261.0  1172.0  61.0  197.0  736.0  115.0  38.0   
3  149.0  116.0  151.0  209.0   813.0  40.0  173.0  661.0   93.0  21.0   
4  170.0   99.0  136.0  148.0   688.0  29.0  144.0  619.0   86.0  20.0   

      21     22     23     24     25     26     27     28    29     

In [8]:
# Split the single column into multiple columns using the comma as a separator
test1 = test1[0].str.split(',', expand=True)

# Convert the columns to numeric data types
test1 = test1.apply(pd.to_numeric, errors='coerce')

# Display the first few rows of the dataset
print(test1.head())

# Display the shape of the dataset
print("Shape of the dataset:", test1.shape)

# Display the column names and data types
print("Columns and data types:")
print(test1.dtypes)

    0     1      2      3      4       5     6       7      8      9      10   \
0  14.0  69.0  234.0  415.0  215.0  1056.0  29.0   840.0  226.0  265.0  179.0   
1  18.0  92.0  312.0  556.0  292.0  1363.0  29.0  1102.0  271.0  340.0  235.0   
2  21.0  96.0  312.0  560.0  272.0  1240.0  29.0  1025.0  270.0  300.0  221.0   
3  20.0  92.0  312.0  443.0  213.0   845.0  24.0   833.0  179.0  211.0  170.0   
4  22.0  91.0  312.0  346.0  190.0   647.0  16.0   733.0  186.0  179.0  142.0   

     11     12     13     14      15    16     17     18     19    20   \
0  148.0  112.0  171.0  229.0  1001.0  49.0  162.0  594.0   88.0  34.0   
1  192.0  143.0  213.0  301.0  1223.0  64.0  216.0  758.0  126.0  39.0   
2  171.0  132.0  185.0  261.0  1172.0  61.0  197.0  736.0  115.0  38.0   
3  149.0  116.0  151.0  209.0   813.0  40.0  173.0  661.0   93.0  21.0   
4  170.0   99.0  136.0  148.0   688.0  29.0  144.0  619.0   86.0  20.0   

      21     22     23     24     25     26     27     28    29     

In [24]:
import numpy as np

# Assuming your dataset is already defined as test1

# Convert your dataset to a NumPy array
data_array = np.array(test1)

# Print the shape of your dataset
print(data_array.shape)

(26304, 321)


In [10]:
import numpy as np
from tqdm import tqdm

# Assuming your dataset is already defined as test1

# Convert your dataset to a NumPy array
data_array = np.array(test1)

# Define the jitter function
def jitter(x, sigma=0.03):
    # https://arxiv.org/pdf/1706.00527.pdf
    return x + np.random.normal(loc=0., scale=sigma, size=x.shape)

# Define the scaling function for 2-dimensional dataset
def scaling(x, sigma=0.1):
    # https://arxiv.org/pdf/1706.00527.pdf
    factor = np.random.normal(loc=1., scale=sigma, size=(x.shape[0],))
    return np.multiply(x, factor[:, np.newaxis])

# Apply the jitter function to your dataset
jittered_data = jitter(data_array)

# Apply the scaling function to your dataset
scaled_data = scaling(data_array)

In [53]:
def rotation(x):
    flip = np.random.choice([-1, 1], size=(x.shape[0],))
    return flip[:, np.newaxis] * x


import random
def permutation(x, max_segments=5, seg_mode="equal"):
    orig_steps = np.arange(x.shape[1])

    num_segs = np.random.randint(1, max_segments, size=(x.shape[0]))

    ret = np.zeros_like(x)
    for i, pat in enumerate(x):
        if num_segs[i] > 1:
            if seg_mode == "random":
                split_points = np.random.choice(x.shape[1]-2, num_segs[i]-1, replace=False)
                split_points.sort()
                splits = np.split(orig_steps, split_points)
            else:
                splits = np.array_split(orig_steps, num_segs[i])
            shuffled_splits = random.sample(splits, len(splits))
            warp = np.concatenate(shuffled_splits).ravel()
            ret[i, :len(warp)] = pat[warp]
        else:
            ret[i] = pat
    return ret


def magnitude_warp(x, sigma=0.2, knot=4):
    from scipy.interpolate import CubicSpline
    orig_steps = np.arange(x.shape[1])
    
    random_warps = np.random.normal(loc=1.0, scale=sigma, size=(x.shape[0], knot+2))
    warp_steps = (np.ones((1,))*(np.linspace(0, x.shape[1]-1., num=knot+2))).T
    ret = np.zeros_like(x)
    for i, pat in enumerate(x):
        warper = np.array([CubicSpline(warp_steps, random_warps[i,:])(orig_steps)]).T
        ret[i] = pat * warper

    return ret


def time_warp(x, sigma=0.2, knot=4):
    from scipy.interpolate import CubicSpline
    orig_steps = np.arange(x.shape[1])
    
    random_warps = np.random.normal(loc=1.0, scale=sigma, size=(x.shape[0], knot+2, x.shape[2]))
    warp_steps = (np.ones((x.shape[2],1))*(np.linspace(0, x.shape[1]-1., num=knot+2))).T
    
    ret = np.zeros_like(x)
    for i, pat in enumerate(x):
        for dim in range(x.shape[2]):
            time_warp = CubicSpline(warp_steps[:,dim], warp_steps[:,dim] * random_warps[i,:,dim])(orig_steps)
            scale = (x.shape[1]-1)/time_warp[-1]
            ret[i,:,dim] = np.interp(orig_steps, np.clip(scale*time_warp, 0, x.shape[1]-1), pat[:,dim]).T
    return ret

def window_slice(x, reduce_ratio=0.9):
    # https://halshs.archives-ouvertes.fr/halshs-01357973/document
    target_len = np.ceil(reduce_ratio*x.shape[1]).astype(int)
    if target_len >= x.shape[1]:
        return x
    starts = np.random.randint(low=0, high=x.shape[1]-target_len, size=(x.shape[0])).astype(int)
    ends = (target_len + starts).astype(int)
    
    ret = np.zeros_like(x)
    for i, pat in enumerate(x):
        for dim in range(x.shape[2]):
            ret[i,:,dim] = np.interp(np.linspace(0, target_len, num=x.shape[1]), np.arange(target_len), pat[starts[i]:ends[i],dim]).T
    return ret

def window_warp(x, window_ratio=0.1, scales=[0.5, 2.]):
    # https://halshs.archives-ouvertes.fr/halshs-01357973/document
    warp_scales = np.random.choice(scales, x.shape[0])
    warp_size = np.ceil(window_ratio*x.shape[1]).astype(int)
    window_steps = np.arange(warp_size)
        
    window_starts = np.random.randint(low=1, high=x.shape[1]-warp_size-1, size=(x.shape[0])).astype(int)
    window_ends = (window_starts + warp_size).astype(int)
            
    ret = np.zeros_like(x)
    for i, pat in enumerate(x):
        for dim in range(x.shape[2]):
            start_seg = pat[:window_starts[i],dim]
            window_seg = np.interp(np.linspace(0, warp_size-1, num=int(warp_size*warp_scales[i])), window_steps, pat[window_starts[i]:window_ends[i],dim])
            end_seg = pat[window_ends[i]:,dim]
            warped = np.concatenate((start_seg, window_seg, end_seg))                
            ret[i,:,dim] = np.interp(np.arange(x.shape[1]), np.linspace(0, x.shape[1]-1., num=warped.size), warped).T
    return ret

def spawner(x, labels, sigma=0.05, verbose=0):
    # https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6983028/
    # use verbose=-1 to turn off warnings
    # use verbose=1 to print out figures
    
    import utils.dtw as dtw
    slope_constraint="symmetric"
    random_points = np.random.randint(low=1, high=x.shape[1]-1, size=x.shape[0])
    window = np.ceil(x.shape[1] / 10.).astype(int)
    orig_steps = np.arange(x.shape[1])
    l = np.argmax(labels, axis=1) if labels.ndim > 1 else labels
    
    ret = np.zeros_like(x)
    for i, pat in enumerate(tqdm(x)):
        # guarentees that same one isnt selected
        choices = np.delete(np.arange(x.shape[0]), i)
        # remove ones of different classes
        choices = np.where(l[choices] == l[i])[0]
        if choices.size > 0:     
            random_sample = x[np.random.choice(choices)]
            # SPAWNER splits the path into two randomly
            path1 = dtw.dtw(pat[:random_points[i]], random_sample[:random_points[i]], dtw.RETURN_PATH, slope_constraint=slope_constraint, window=window)
            path2 = dtw.dtw(pat[random_points[i]:], random_sample[random_points[i]:], dtw.RETURN_PATH, slope_constraint=slope_constraint, window=window)
            combined = np.concatenate((np.vstack(path1), np.vstack(path2+random_points[i])), axis=1)
            if verbose:
                print(random_points[i])
                dtw_value, cost, DTW_map, path = dtw.dtw(pat, random_sample, return_flag = dtw.RETURN_ALL, slope_constraint=slope_constraint, window=window)
                dtw.draw_graph1d(cost, DTW_map, path, pat, random_sample)
                dtw.draw_graph1d(cost, DTW_map, combined, pat, random_sample)
            mean = np.mean([pat[combined[0]], random_sample[combined[1]]], axis=0)
            for dim in range(x.shape[2]):
                ret[i,:,dim] = np.interp(orig_steps, np.linspace(0, x.shape[1]-1., num=mean.shape[0]), mean[:,dim]).T
        else:
            if verbose > -1:
                print("There is only one pattern of class %d, skipping pattern average"%l[i])
            ret[i,:] = pat
    return jitter(ret, sigma=sigma)

def wdba(x, labels, batch_size=6, slope_constraint="symmetric", use_window=True, verbose=0):
    # https://ieeexplore.ieee.org/document/8215569
    # use verbose = -1 to turn off warnings    
    # slope_constraint is for DTW. "symmetric" or "asymmetric"
    
    import utils.dtw as dtw
    
    if use_window:
        window = np.ceil(x.shape[1] / 10.).astype(int)
    else:
        window = None
    orig_steps = np.arange(x.shape[1])
    l = np.argmax(labels, axis=1) if labels.ndim > 1 else labels
        
    ret = np.zeros_like(x)
    for i in tqdm(range(ret.shape[0])):
        # get the same class as i
        choices = np.where(l == l[i])[0]
        if choices.size > 0:        
            # pick random intra-class pattern
            k = min(choices.size, batch_size)
            random_prototypes = x[np.random.choice(choices, k, replace=False)]
            
            # calculate dtw between all
            dtw_matrix = np.zeros((k, k))
            for p, prototype in enumerate(random_prototypes):
                for s, sample in enumerate(random_prototypes):
                    if p == s:
                        dtw_matrix[p, s] = 0.
                    else:
                        dtw_matrix[p, s] = dtw.dtw(prototype, sample, dtw.RETURN_VALUE, slope_constraint=slope_constraint, window=window)
                        
            # get medoid
            medoid_id = np.argsort(np.sum(dtw_matrix, axis=1))[0]
            nearest_order = np.argsort(dtw_matrix[medoid_id])
            medoid_pattern = random_prototypes[medoid_id]
            
            # start weighted DBA
            average_pattern = np.zeros_like(medoid_pattern)
            weighted_sums = np.zeros((medoid_pattern.shape[0]))
            for nid in nearest_order:
                if nid == medoid_id or dtw_matrix[medoid_id, nearest_order[1]] == 0.:
                    average_pattern += medoid_pattern 
                    weighted_sums += np.ones_like(weighted_sums) 
                else:
                    path = dtw.dtw(medoid_pattern, random_prototypes[nid], dtw.RETURN_PATH, slope_constraint=slope_constraint, window=window)
                    dtw_value = dtw_matrix[medoid_id, nid]
                    warped = random_prototypes[nid, path[1]]
                    weight = np.exp(np.log(0.5)*dtw_value/dtw_matrix[medoid_id, nearest_order[1]])
                    average_pattern[path[0]] += weight * warped
                    weighted_sums[path[0]] += weight 
            
            ret[i,:] = average_pattern / weighted_sums[:,np.newaxis]
        else:
            if verbose > -1:
                print("There is only one pattern of class %d, skipping pattern average"%l[i])
            ret[i,:] = x[i]
    return ret

# Proposed

def random_guided_warp(x, labels, slope_constraint="symmetric", use_window=True, dtw_type="normal", verbose=0):
    # use verbose = -1 to turn off warnings
    # slope_constraint is for DTW. "symmetric" or "asymmetric"
    # dtw_type is for shapeDTW or DTW. "normal" or "shape"
    
    import utils.dtw as dtw
    
    if use_window:
        window = np.ceil(x.shape[1] / 10.).astype(int)
    else:
        window = None
    orig_steps = np.arange(x.shape[1])
    l = np.argmax(labels, axis=1) if labels.ndim > 1 else labels
    
    ret = np.zeros_like(x)
    for i, pat in enumerate(tqdm(x)):
        # guarentees that same one isnt selected
        choices = np.delete(np.arange(x.shape[0]), i)
        # remove ones of different classes
        choices = np.where(l[choices] == l[i])[0]
        if choices.size > 0:        
            # pick random intra-class pattern
            random_prototype = x[np.random.choice(choices)]
            
            if dtw_type == "shape":
                path = dtw.shape_dtw(random_prototype, pat, dtw.RETURN_PATH, slope_constraint=slope_constraint, window=window)
            else:
                path = dtw.dtw(random_prototype, pat, dtw.RETURN_PATH, slope_constraint=slope_constraint, window=window)
                            
            # Time warp
            warped = pat[path[1]]
            for dim in range(x.shape[2]):
                ret[i,:,dim] = np.interp(orig_steps, np.linspace(0, x.shape[1]-1., num=warped.shape[0]), warped[:,dim]).T
        else:
            if verbose > -1:
                print("There is only one pattern of class %d, skipping timewarping"%l[i])
            ret[i,:] = pat
    return ret

def random_guided_warp_shape(x, labels, slope_constraint="symmetric", use_window=True):
    return random_guided_warp(x, labels, slope_constraint, use_window, dtw_type="shape")

def discriminative_guided_warp(x, labels, batch_size=6, slope_constraint="symmetric", use_window=True, dtw_type="normal", use_variable_slice=True, verbose=0):
    # use verbose = -1 to turn off warnings
    # slope_constraint is for DTW. "symmetric" or "asymmetric"
    # dtw_type is for shapeDTW or DTW. "normal" or "shape"
    
    import utils.dtw as dtw
    
    if use_window:
        window = np.ceil(x.shape[1] / 10.).astype(int)
    else:
        window = None
    orig_steps = np.arange(x.shape[1])
    l = np.argmax(labels, axis=1) if labels.ndim > 1 else labels
    
    positive_batch = np.ceil(batch_size / 2).astype(int)
    negative_batch = np.floor(batch_size / 2).astype(int)
        
    ret = np.zeros_like(x)
    warp_amount = np.zeros(x.shape[0])
    for i, pat in enumerate(tqdm(x)):
        # guarentees that same one isnt selected
        choices = np.delete(np.arange(x.shape[0]), i)
        
        # remove ones of different classes
        positive = np.where(l[choices] == l[i])[0]
        negative = np.where(l[choices] != l[i])[0]
        
        if positive.size > 0 and negative.size > 0:
            pos_k = min(positive.size, positive_batch)
            neg_k = min(negative.size, negative_batch)
            positive_prototypes = x[np.random.choice(positive, pos_k, replace=False)]
            negative_prototypes = x[np.random.choice(negative, neg_k, replace=False)]
                        
            # vector embedding and nearest prototype in one
            pos_aves = np.zeros((pos_k))
            neg_aves = np.zeros((pos_k))
            if dtw_type == "shape":
                for p, pos_prot in enumerate(positive_prototypes):
                    for ps, pos_samp in enumerate(positive_prototypes):
                        if p != ps:
                            pos_aves[p] += (1./(pos_k-1.))*dtw.shape_dtw(pos_prot, pos_samp, dtw.RETURN_VALUE, slope_constraint=slope_constraint, window=window)
                    for ns, neg_samp in enumerate(negative_prototypes):
                        neg_aves[p] += (1./neg_k)*dtw.shape_dtw(pos_prot, neg_samp, dtw.RETURN_VALUE, slope_constraint=slope_constraint, window=window)
                selected_id = np.argmax(neg_aves - pos_aves)
                path = dtw.shape_dtw(positive_prototypes[selected_id], pat, dtw.RETURN_PATH, slope_constraint=slope_constraint, window=window)
            else:
                for p, pos_prot in enumerate(positive_prototypes):
                    for ps, pos_samp in enumerate(positive_prototypes):
                        if p != ps:
                            pos_aves[p] += (1./(pos_k-1.))*dtw.dtw(pos_prot, pos_samp, dtw.RETURN_VALUE, slope_constraint=slope_constraint, window=window)
                    for ns, neg_samp in enumerate(negative_prototypes):
                        neg_aves[p] += (1./neg_k)*dtw.dtw(pos_prot, neg_samp, dtw.RETURN_VALUE, slope_constraint=slope_constraint, window=window)
                selected_id = np.argmax(neg_aves - pos_aves)
                path = dtw.dtw(positive_prototypes[selected_id], pat, dtw.RETURN_PATH, slope_constraint=slope_constraint, window=window)
                   
            # Time warp
            warped = pat[path[1]]
            warp_path_interp = np.interp(orig_steps, np.linspace(0, x.shape[1]-1., num=warped.shape[0]), path[1])
            warp_amount[i] = np.sum(np.abs(orig_steps-warp_path_interp))
            for dim in range(x.shape[2]):
                ret[i,:,dim] = np.interp(orig_steps, np.linspace(0, x.shape[1]-1., num=warped.shape[0]), warped[:,dim]).T
        else:
            if verbose > -1:
                print("There is only one pattern of class %d"%l[i])
            ret[i,:] = pat
            warp_amount[i] = 0.
    if use_variable_slice:
        max_warp = np.max(warp_amount)
        if max_warp == 0:
            # unchanged
            ret = window_slice(ret, reduce_ratio=0.9)
        else:
            for i, pat in enumerate(ret):
                # Variable Sllicing
                ret[i] = window_slice(pat[np.newaxis,:,:], reduce_ratio=0.9+0.1*warp_amount[i]/max_warp)[0]
    return ret

def discriminative_guided_warp_shape(x, labels, batch_size=6, slope_constraint="symmetric", use_window=True):
    return discriminative_guided_warp(x, labels, batch_size, slope_constraint, use_window, dtw_type="shape")

In [54]:
# Apply the jitter function to your dataset
rotated_data = rotation(data_array)

# Apply the scaling function to your dataset
permuted_data = permutation(data_array, max_segments=5, seg_mode="equal")

# # Apply the jitter function to your dataset
# magnwarped_data = magnitude_warp(data_array)

# # Apply the scaling function to your dataset
# timewarped_data = time_warp(data_array)


# # Apply the jitter function to your dataset
# windowssliced_data = window_slice(data_array)

# # Apply the scaling function to your dataset
# windowwarped_data = window_warp(data_array)

# # Apply the jitter function to your dataset
# spawnered_data = spawner(data_array)

# # Apply the scaling function to your dataset
# wdba_data = wdba(data_array)

# # Apply the jitter function to your dataset
# random_guided_warp_data = random_guided_warp(data_array)

# # Apply the scaling function to your dataset
# discriminative_guided_warp_data = discriminative_guided_warp(data_array)

In [55]:
# Print the first 5 rows of the original dataset
print("Original dataset:")
print(data_array[:5])

# Print the first 5 rows of the jittered dataset
print("\nJittered dataset:")
print(jittered_data[:5])

# Print the first 5 rows of the scaled dataset
print("\nScaled dataset:")
print(scaled_data[:5])

# Print the first 5 rows of the rotated dataset
print("\nRotated dataset:")
print(rotated_data[:5])

print("\permuted dataset:")
print(permuted_data[:5])

Original dataset:
[[  14.   69.  234. ... 1558.  182. 2162.]
 [  18.   92.  312. ... 2177.  253. 2835.]
 [  21.   96.  312. ... 2193.  218. 2764.]
 [  20.   92.  312. ... 1315.  195. 2735.]
 [  22.   91.  312. ... 1378.  191. 2721.]]

Jittered dataset:
[[  14.04170154   69.02699878  234.01102829 ... 1557.9972927
   181.9573926  2161.99185736]
 [  17.99030703   91.9933798   311.99929844 ... 2176.97031363
   253.00261659 2835.01513855]
 [  21.04443805   96.0465942   312.04568473 ... 2193.04877963
   217.98179642 2763.98065414]
 [  19.98512177   91.95323707  312.05015266 ... 1314.96647421
   194.98120737 2734.98041091]
 [  22.00911494   90.99712006  311.97948562 ... 1378.01331348
   190.98128175 2720.97151996]]

Scaled dataset:
[[  13.42889358   66.18526122  224.45436414 ... 1494.44401425
   174.57561656 2073.80485161]
 [  16.19299211   82.76418187  280.67852982 ... 1958.45243406
   227.60150015 2550.39625658]
 [  20.94325927   95.74061382  311.15699491 ... 2187.07464691
   217.41097721 2

In [57]:
import numpy as np
import pandas as pd
from statsmodels.tsa.arima.model import ARIMA

# Assuming your dataset is a 2D numpy array named 'data_array'
# with shape (samples, time_steps)

# Select one sample (time series) from your dataset for demonstration
sample_ts = data_array[0]

# Fit the ARIMA model
model = ARIMA(sample_ts, order=(1, 0, 0))  # (p, d, q) - (AR order, differencing, MA order)
model_fit = model.fit()

# Forecast the next 5 time steps
forecast_steps = 5
forecast = model_fit.forecast(steps=forecast_steps)
print(f"Forecasted values: {forecast}")

Forecasted values: [1319.16998756 1300.97766462 1300.58498685 1300.57651097 1300.57632802]
